// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ptOI37iWtFnp8x-PJoQkzmOl0OCB2o8',
    appId: '1:878527192179:web:86cc8dafa6e693c0a85e06',
    messagingSenderId: '878527192179',
    projectId: 'chatapp-9f9e7',
    authDomain: 'chatapp-9f9e7.firebaseapp.com',
    storageBucket: 'chatapp-9f9e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzmbalF5e6nC6Q6ze2XcsHoyLoFITcdj8',
    appId: '1:878527192179:android:59bf7c5798773830a85e06',
    messagingSenderId: '878527192179',
    projectId: 'chatapp-9f9e7',
    storageBucket: 'chatapp-9f9e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKhgf3vcolIKLYoVFl3bV6G_2dX6YI9tY',
    appId: '1:878527192179:ios:3a8d322df37bb65aa85e06',
    messagingSenderId: '878527192179',
    projectId: 'chatapp-9f9e7',
    storageBucket: 'chatapp-9f9e7.appspot.com',
    iosBundleId: 'com.example.appChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKhgf3vcolIKLYoVFl3bV6G_2dX6YI9tY',
    appId: '1:878527192179:ios:fadd9b8d661a4eaba85e06',
    messagingSenderId: '878527192179',
    projectId: 'chatapp-9f9e7',
    storageBucket: 'chatapp-9f9e7.appspot.com',
    iosBundleId: 'com.example.appChat.RunnerTests',
  );
}
